# Generated by Django 5.0.6 on 2026-01-14 21:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('geofence_type', models.CharField(choices=[('circle', 'Circle')], default='circle', max_length=10)),
                ('center_latitude', models.FloatField(help_text='Center latitude for circle geofence')),
                ('center_longitude', models.FloatField(help_text='Center longitude for circle geofence')),
                ('radius', models.FloatField(help_text='Radius in meters for circle geofence')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofences', to='vehicles.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='vehicles.organization')),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('car', 'Car'), ('truck', 'Truck'), ('van', 'Van'), ('taxi', 'Taxi'), ('moto', 'Moto'), ('bus', 'Bus'), ('delivery', 'Delivery')], max_length=10)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('vin', models.CharField(blank=True, help_text='Vehicle Identification Number', max_length=17)),
                ('last_latitude', models.FloatField(blank=True, help_text='Last known latitude', null=True)),
                ('last_longitude', models.FloatField(blank=True, help_text='Last known longitude', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('fuel_level', models.FloatField(default=100.0, help_text='Fuel level in percentage')),
                ('odometer', models.FloatField(default=0.0, help_text='Odometer reading in km')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance'), ('out_of_service', 'Out of Service')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('max_speed', models.FloatField(blank=True, help_text='Maximum allowed speed in km/h', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_vehicle', to='vehicles.driver')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='vehicles.organization')),
            ],
            options={
                'ordering': ['plate'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('start_latitude', models.FloatField()),
                ('start_longitude', models.FloatField()),
                ('end_latitude', models.FloatField(blank=True, null=True)),
                ('end_longitude', models.FloatField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, help_text='Total distance in km', null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('max_speed', models.FloatField(blank=True, help_text='Maximum speed during trip in km/h', null=True)),
                ('avg_speed', models.FloatField(blank=True, help_text='Average speed in km/h', null=True)),
                ('fuel_consumed', models.FloatField(blank=True, help_text='Fuel consumed in liters', null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='vehicles.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('oil_change', 'Oil Change'), ('tire_rotation', 'Tire Rotation'), ('brake_service', 'Brake Service'), ('inspection', 'Inspection'), ('repair', 'Repair'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('odometer_reading', models.FloatField(help_text='Odometer reading at maintenance in km')),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('performed_by', models.CharField(blank=True, max_length=200)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('next_service_odometer', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('speed', models.FloatField(default=0.0, help_text='Speed in km/h')),
                ('heading', models.FloatField(blank=True, help_text='Direction in degrees (0-360)', null=True)),
                ('altitude', models.FloatField(blank=True, help_text='Altitude in meters', null=True)),
                ('accuracy', models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True)),
                ('battery_level', models.FloatField(blank=True, null=True)),
                ('is_ignition_on', models.BooleanField(default=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GeofenceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit')], max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('geofence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='vehicles.geofence')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_alerts', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['last_latitude', 'last_longitude'], name='vehicles_ve_last_la_9c898e_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['vehicle', '-start_time'], name='vehicles_tr_vehicle_4f05be_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['driver', '-start_time'], name='vehicles_tr_driver__5775de_idx'),
        ),
        migrations.AddIndex(
            model_name='locationhistory',
            index=models.Index(fields=['vehicle', '-timestamp'], name='vehicles_lo_vehicle_7dfe09_idx'),
        ),
        migrations.AddIndex(
            model_name='locationhistory',
            index=models.Index(fields=['timestamp'], name='vehicles_lo_timesta_841fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='locationhistory',
            index=models.Index(fields=['latitude', 'longitude'], name='vehicles_lo_latitud_462674_idx'),
        ),
        migrations.AddIndex(
            model_name='geofencealert',
            index=models.Index(fields=['-timestamp'], name='vehicles_ge_timesta_235d3b_idx'),
        ),
        migrations.AddIndex(
            model_name='geofencealert',
            index=models.Index(fields=['vehicle', '-timestamp'], name='vehicles_ge_vehicle_9b33b7_idx'),
        ),
    ]
